name: rpmtranslator
description: RPMTW Translator

publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  url_launcher: ^6.0.20
  path: ^1.8.1
  auto_size_text: 3.0.0-nullsafety.0
  split_view:
  oauth2:
  html: ^0.15.0
  highlight_text: ^1.1.0
  universal_io: ^2.0.4
  universal_html: ^2.0.8
  url_strategy: ^0.2.0
  flutter_svg: ^1.0.3
  rpmtw_api_client_flutter: ^1.0.8-dev.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: font
      fonts:
        - asset: assets/fonts/NotoSansCJKtc-Regular.otf #Source: https://www.google.com/get/noto/
